name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-gcc12:
    runs-on: ubuntu-latest
    name: GNU GCC 12
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install GCC 12
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-12 g++-12
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-gcc14:
    runs-on: ubuntu-latest
    name: GNU GCC 14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install GCC 14
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang13:
    runs-on: ubuntu-22.04
    name: Clang 13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Clang 13
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-13
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang14:
    runs-on: ubuntu-22.04
    name: Clang 14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Clang 14
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-14
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang13-asan:
    runs-on: ubuntu-22.04
    name: Clang 13 + ASAN
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Clang 13
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-13
      - name: Build rinox with ASAN
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DRINOX_ENABLE_ASAN=ON -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests with ASAN
        run: |
          cd build
          ./test/run_unit_tests