name: Linux CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-gcc9:
    runs-on: ubuntu-latest
    name: GNU GCC 9
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install GCC 9
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-9
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++-9 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-gcc10:
    runs-on: ubuntu-latest
    name: GNU GCC 10
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install GCC 10
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-10
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++-10 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-gcc10-cpp20:
    runs-on: ubuntu-latest
    name: GNU GCC 10 (C++20)
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install GCC 10
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-10 g++-10
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DRINOX_CXX_STANDARD=20 -DCMAKE_CXX_COMPILER=g++-10 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-gcc12:
    runs-on: ubuntu-latest
    name: GNU GCC 12
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install GCC 12
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++-12 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang11:
    runs-on: ubuntu-22.04
    name: Clang 11
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Clang 11
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-11
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++-11 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang13:
    runs-on: ubuntu-22.04
    name: Clang 13
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Clang 13
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-13
      - name: Build rinox
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++-13 -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang13-asan:
    runs-on: ubuntu-22.04
    name: Clang 13 + ASAN
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Clang 13
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-13
      - name: Build rinox with ASAN
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++-13 -DENABLE_ASAN=ON -DRINOX_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests with ASAN
        run: |
          cd build
          ./test/run_unit_tests

  compile-gcc9:
    runs-on: ubuntu-latest
    name: Compile everything (GCC 9)
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install GCC 9
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-9
      - name: Build rinox (full)
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++-9 -DRINOX_ENABLE_EXAMPLES=ON -DRINOX_ENABLE_EXPERIMENTS=ON -DRINOX_ENABLE_TESTS=ON ..
          make
