name: macOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ---- Removed GCC 12 build on macOS ----
  # macOS + GCC 12 is broken due to SDK incompatibility.
  # If you need GCC coverage, test it on Ubuntu instead.

  build-clang14:
    name: Clang 14 (System)
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build rinox
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
            -DRINOX_ENABLE_TESTS=ON
          make run_unit_tests

      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang17:
    name: Clang 17 (Homebrew)
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install LLVM 17
        run: |
          brew update
          brew install llvm@17

      - name: Build rinox
        run: |
          LLVM_PREFIX=$(brew --prefix llvm@17)
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER="${LLVM_PREFIX}/bin/clang" \
            -DCMAKE_CXX_COMPILER="${LLVM_PREFIX}/bin/clang++" \
            -DRINOX_ENABLE_TESTS=ON
          make run_unit_tests

      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests
