name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gcc12:
    name: GNU GCC 12
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build mad-hatter
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=$(which g++-12) -DHATTER_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang14:
    name: Clang 14
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build mad-hatter
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DHATTER_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests

  build-clang15:
    name: Clang 15
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install LLVM 15
        run: |
          brew update
          brew install llvm@15
      - name: Build mad-hatter
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++ -DHATTER_ENABLE_TESTS=ON ..
          make run_unit_tests
      - name: Run tests
        run: |
          cd build
          ./test/run_unit_tests
