name: Windows CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022 ]
        toolset: [ v142, ClangCL ]
        include:
          - os: windows-2022
            env: "Visual Studio 17 2022"

    name: ${{matrix.os}} with ${{matrix.env}} and ${{matrix.toolset}} toolset
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Clean build
        run: cmake -E remove_directory build

      - name: Create build directory
        run: cmake -E make_directory ${{github.workspace}}\build

      - name: Run CMake
        run: >
          cmake ${{github.workspace}}
          -G "${{matrix.env}}"
          -A x64
          -T ${{matrix.toolset}}
          -DRINOX_ENABLE_TESTS=ON
        working-directory: ${{github.workspace}}\build

      - name: Build rinox
        run: cmake --build . --config Debug -j2
        working-directory: ${{github.workspace}}\build
        shell: cmd

      - name: Run unit tests
        run: .\test\Debug\run_unit_tests --durations yes --reporter console
        working-directory: ${{github.workspace}}\build
        shell: cmd
